### ISSUE TITLE
A small preformance optimization?

### ISSUE THREAD

**Issue by Tsukulimer** [phoboslab/qoa#61]
**qoa_decode_frame()** uses **qoa_clamp()** to find slice_end
    `int slice_end = qoa_clamp(sample_index + QOA_SLICE_LEN, 0, samples) * channels + c;`

so it checks **if (v < min)** for every sample in every channel
But slice_end just can't be less than 0
it equals **sample_index (0 or more) + QOA_SLICE_LEN (1 or more) * channels (1 or more) + c (0 or more)** 

It would be faster to find slice_end like this:
`int slice_end = qoa_min(sample_index + QOA_SLICE_LEN, samples) * channels + c;`

**slice_len** in **qoa_encode_frame()** can benefit from **qoa_min()** too

**Comment by phoboslab** [comment]
I don't think it this could have a measurable effect, since it's not in the hot inner loop. Also, this function is inlined and sample_index is unsigned,so I feel that my compiler should be smart enough to figure out that a simple min() would suffice :)

I'm closing this issue, but if you can demonstrate a performance improvement, please feel free to reopen.
